[package]
name = "rlbot"
version = "0.0.2"
authors = ["John Simon <john@whatisaph.one>"]
description = "RLBot bindings for Rust"
documentation = "https://docs.rs/rlbot/"
repository = "https://gitlab.com/whatisaphone/rlbot-rust"
readme = "README-crates-io.md"
keywords = ["rlbot", "rocket-league", "game"]
license = "MIT"

[badges]
gitlab = { repository = "whatisaphone/rlbot-rust" }

[dependencies]
libloading = "0.5.0"
ratelimit = "0.4.3"

[dev-dependencies]
nalgebra = "0.16.0"
